---
- name: Baixa o kubectl da release estável oficial
  ansible.builtin.shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  args:
    chdir: /tmp
    creates: /tmp/kubectl

- name: Move o kubectl para /usr/local/bin e define permissão
  ansible.builtin.copy:
    src: /tmp/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    remote_src: yes
